apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: codeforces-clone
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: codeforces-clone
    component: backend
