apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: codeforces-clone
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: codeforces-clone
    component: frontend
